FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Base packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
