name: Build

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build
        run: go build -o doozer-scaffold ./cmd/doozer-scaffold
